name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t rosariowrobel/mi-api:${{ github.sha }} .
          docker push rosariowrobel/mi-api:${{ github.sha }}

      # 4. Deploy to ECS
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster API-Cluster \
            --service api-service \
            --force-new-deployment
