name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 982081066879.dkr.ecr.us-east-2.amazonaws.com

      # 3. Build and push Docker image to ECR
      - name: Build and push Docker image
        run: |
          docker build -t 982081066879.dkr.ecr.us-east-2.amazonaws.com/mi-aplicacion-node:${{ github.sha }} .
          docker push 982081066879.dkr.ecr.us-east-2.amazonaws.com/mi-aplicacion-node:${{ github.sha }}

      # 4. Deploy to ECS
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster mi-cluster-ecs \
            --service mi-api-service \
            --force-new-deployment \
            --task-definition Microservicio-task-4:1 \
            --image 982081066879.dkr.ecr.us-east-2.amazonaws.com/mi-aplicacion-node:${{ github.sha }}
